version: '3'

services:
 app-server:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8081:8081"
  restart: always
  depends_on: 
   db:
    condition: service_healthy
   
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eva?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
   SPRING_DATASOURCE_USERNAME: user
   SPRING_DATASOURCE_PASSWORD: userpass
   SPRING_PROFILES_ACTIVE: prod
 db:
  image: mysql:8.0
  ports:
   - "3306:3306"
  restart: always
  environment:
   MYSQL_DATABASE: eva
   MYSQL_USER: user
   MYSQL_PASSWORD: userpass
   MYSQL_ROOT_PASSWORD: root
  healthcheck:
   test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD